"""Local object store for uploaded archives."""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import BinaryIO

from .config import Config


class LocalStore:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def put(self, bucket: str, key: str, src: BinaryIO) -> None:
        path = self._path(bucket, key)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("wb") as out:
            shutil.copyfileobj(src, out)

    def get_bytes(self, bucket: str, key: str) -> bytes:
        return self._path(bucket, key).read_bytes()

    def open(self, bucket: str, key: str):
        return self._path(bucket, key).open("rb")

    def _path(self, bucket: str, key: str) -> Path:
        # Keys are generated by the API (org + uuid). Refuse traversal anyway.
        rel = Path(bucket) / Path(key)
        if any(part in ("", ".", "..") for part in rel.parts):
            raise ValueError("unsafe object key")
        path = (self.root / rel).resolve()
        if not str(path).startswith(str(self.root.resolve())):
            raise ValueError("unsafe object key")
        return path


def open_store(cfg: Config) -> LocalStore:
    root = Path(cfg.object_root)
    if not root.is_absolute():
        root = Path.cwd() / root
    return LocalStore(root)
